package user.Patient;

/**  
    This is a list of health problems that are shown in the selection.
    *@author Prabal, Daniel, Houda , Amine , Ahmed
*/
   
public enum HealthProblem {
    Asthma,
    Eczema,
    Food_allergies,
    Insect_sting_allergies,
    Heart_Problem,
    Heart_Failure,
    Heart_Attack,
    High_blood_pressure,
    Irregular_heartbeat,
    Colon_cancer,
    Hemorrhoids,
    Inflammatory_bowel,
    Moles,
    Scars,
    Acne,
    Skin_allergies,
    Diabetes,
    Thyroid_problems,
    Infertility,
    Bone_disorder,
    Routine_checkup,
    Abdominal_pain,
    Ulcers,
    Diarrhea,
    Jaundice,
    Sickle_cell,
    Anemia,
    Hemophilia,
    Leukemia,
    Fevers,
    Lyme,
    Pneumonia,
    Tuberculosis,
    HIV,
    AIDS,
    Kidney_disease,
    Strokes,
    Brain_problem,
    Spinal_tumors,
    Epilepsy,
    Parkinson,
    Alzheimer,
    Glaucoma,
    Eye_problem,
    Ears_problem,
    Nose_problem,
    Throat__problem,
    Sinuses_problem,
    Head_problem,
    Neck_problem,
    Respiratory_system_problem,
    Depression,
    Schizophrenia,
    Substance_abuse,
    Anxiety,
    Lung_cancer,
    Emphysema,
    Osteoporosis,
    Back_pain,
    Gout,
    Tendinitis,
    Fibromyalgia,
    Immune_System_Problems,
    Allergies,
    Flu,
    Cold,
    Conjunctivitis,
    Mononucleosis,
    Intestinal_Gas,
    Nausea_and_Vomiting,
    Headache


}
